name: Example / Form type issue template
description: https://github.com/kachick/times_kachick/issues/147
title: "Form type issue template test / "
labels: [とある日本語ラベル, needs triage]
assignees:
  - kachick
  - pankona
body:
  - type: textarea
    id: background
    attributes:
      label: 現状の問題点・動機・背景
      description: 雑でも伝われば構わない
      value: |
        1. さっき URL1 が発生した
        2. それは URL2 とかの理由から、好ましくない
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: How(案)
      description: なんか案とか方策があれば適当に書き殴る。無ければ空で良い
      value: "風の吹くまま気の向くまま"
    validations:
      required: false
  - type: textarea
    id: links
    attributes:
      label: Links/References
      description: 関連する issue/PR/slack/参考資料 等があれば貼っておく
      value: |
        - https://github.com/kachick/times_kachick/issues/147
        - [参考資料](参考資料のURL)
    validations:
      required: false
  - type: textarea
    id: mention
    attributes:
      label: Mentions
      description: この issue を適宜気にして欲しい人達へメンションする
      value: "@kachick @pankona"
    validations:
      required: false
